export const SELECT_SERVER = 'SELECT_SERVER';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const ADD_RANDOM_SERVER = 'ADD_RANDOM_SERVER';
export const ADD_RANDOM_CHANNEL = 'ADD_RANDOM_CHANNEL';
export const ADD_RANDOM_MESSAGE = 'ADD_RANDOM_MESSAGE';

export const ADD_USER = 'ADD_USER';
export const USER_JOIN_VOICE = 'USER_JOIN_VOICE';
export const USER_LEAVE_VOICE = 'USER_LEAVE_VOICE';
export const INCREMENT_BITS = 'INCREMENT_BITS';
